MicrosoftDocs/live-share

welcome/welcome-owner.md
Picture attached of how the extension is named in the marketplace.
Open Question: Does the Visual Studio 2017 marketplace also call it VS Live Share and we should update line 24 of this doc as well?
=> Correct extension name.

docs/reference/security.md
* Fixed typos in `.vsls.json` code examples (missing closing quotes)
* General `.md` file formatting fixes
=> Typos and formatting

scripts/linux-prereqs.sh
Script updates to help avoid problems with two versions of libssl being installed (#299) and uninstalling libcurl4 by installing libcurl3 on Ubuntu 18.04 (#428)
=> Install script updates to handle libcurl4 on Ubuntu, double install of libssl on Debian

docs/reference/platform-support.md
Azure Dev Spaces is the new name for VSCE. Updated link for the landing page, too.
=> Updating VSCE -> Azure Dev Spaces

docs/reference/manual-join.md
The links on How-tos are both to VS Code, this fixes the VS link.
=> Manual Join: fix Visual Studio link

scripts/linux-prereqs.sh
=> Fix for removing libssl1.0.0 when to architectures for the library are detected

docs/reference/use-cases.md
=> Swarm, not swam

docs/reference/linux.md, docs/use/vscode.md, scripts/.gitattributes, scripts/linux-prereqs.sh
This is an improved install script that addresses the following issues:
1. .NET Core 2.1 has fewer dependencies than 2.0, so the script is now reduced to known 2.1 deps only.
2. The script no longer requires sudo when running as root
3. The script can optionally skip keyring or browser integration dependencies (via args)
4. The script gracefully waits for existing dpkg operations to complete on Debian/Ubuntu based distros
5. The script no longer checks for libssl1.0.0 + libssl1.0.2 as this is not a problem with .NET Core 2.1
5. Adds Alpine Linux support
Testing on Linux desktop distros:
1. Open a terminal in the distro you want to test
2. Be sure `wget` is available - install it if not
3. Run: `
wget -O ~/vsls-reqs https://raw.githubusercontent.com/MicrosoftDocs/live-share/netcore21-linuxd …
=> Reduce .NET Core deps, handle running as root, conditional install

docs/reference/linux.md, scripts/linux-prereqs.sh
Resolves #1385. Fedora 29 does not appear to install compat-openssl10 with openssl-libs. Update checks for the existence of compat-openssl10 (since it doesn't exist on RHL or CentOS7) and installs it of detected.
=> Fix for Fedora 29

docs/use/vs.md
@@ line 367
old:
```simply needs to hare state button```
@@ line 367
new: ```needs to click the share / session```
=> docs: typo fix

docs/reference/security.md
=> fix: Add code fence language to JSON examples

docs/reference/linux.md
- Spaceing between headers
- Double word "the"
- Space inside code block
- Trim trailing spaces
=> fix: docs/reference/linux.md

docs/reference/security.md
- Adjust list indenting for Markdownlint
- Add code fence language blocks
- Use MSDoc style blockquotes
- gitignores -> gitignore
- Trim trailing spaces
=> fix: docs/reference/security.md

docs/use/vs.md
- Use MSDoc style blockquotes
- Double word "can"
=> fix: docs/use/vs.md

docs/reference/use-cases.md
- Use dashes for unordered lists consistently for Markdownlint
- firedrill -> fire drill
=> fix: docs/reference/use-cases.md

.github/stale.yml
Enables bot from https://github.com/probot/stale to close issues with the "needs more info" that have been inactive for 14 days.
=> Configure bot to close inactive issues after 14 days

scripts/linux-prereqs.sh
Fixes #2812 
Use `libssl-dev` instead of hard-coding the version of libssl for every Ubuntu release. `libssl-dev` is available in Ubuntu going back to 16.04:
https://packages.ubuntu.com/search?keywords=libssl-dev
=> Use libssl-dev on Ubuntu

scripts/linux-prereqs.sh
Since Fedora 30 don't ship yum anymore, a new section to detect the necessity of dnf use is needed.
=> Set a new section for detecting Fedora 30, as it do not ship yum anymore.

docs/quickstart/browser-join.md
I found two typos in the [Joining from the browser](https://docs.microsoft.com/en-us/visualstudio/liveshare/quickstart/browser-join) docs:
- The `description` metadata tag said "Introducing joining from thr browser". I replaced `thr` with `the`
- The first section said "...joined form the browser...". I replaced the `form` with `from`
=> Fixing two typos in "Joining from the browser" docs

docs/use/vscode.md
The existing description of Live Share read/write terminal access doesn't clear explain the privileges granted to the guest user. This commit specifies that the guest has the exact same terminal access as the host. This helps raise awareness of the issue in #3582.
=> Explain shared terminal write access permission

docs/overview/what's-new.md
Assuming this is supposed to be 'in order to use integrated chat'.
I also remove the capitalisation of Integrated, since it's not ~~integrated~~ capitalised in the rest of the document.
=> Fix typo 'in order to user Integrated chat'

scripts/linux-prereqs.sh
On Arch Linux, signing in with a GitHub or Microsoft account requires the xdg-open command which is a part of the xdg-utils package. xdg-utils is a transitive dependency of many desktop environments and the chrome browser, but I did not have it installed, so I was unable to sign in.
=> add xdg-utils dependency for arch linux

docs/reference/use-cases.md
Grammatical errors and typos were introduced in #3873 
This PR addresses issues with possession, spelling, readability, and a missing determiner.
=> Fix grammatical errors in `Working Remotely`

.github/workflows/label-issues.yml
Adding a script to auto-label issues with the product-feedback label on the 1st of each month.
=> Script to auto-assign product-feedback label

docs/toc.md, docs/use/enable-accessibility-features-visual-studio-code.md
These were mistakenly deleted in the refactoring of this repo.
=> Re-add accessibility docs

scripts/linux-prereqs.sh
On Ubuntu 22.04 the libssl1.1 command currently fails without any intervention
This is now checked if libssl1.1 install fails and will print the alternate
installation method of libssl1.1 which basically means
1. Adding `deb http://security.ubuntu.com/ubuntu focal-security main` to `/etc/apt/sources.list`
2. Running `apt update` to include the source
This will resolve #4741 and probably #4710, #4646, #4678
The solution described by @ermshiperete here https://github.com/MicrosoftDocs/live-share/issues/4741#issuecomment-1219238297 should also be into consideration, but I haven't tested it for the whole suite of distributions.
=> refactor: add error message for libssl1.1 on Ubuntu 22.04

docs/toc.md
Release notes are no longer published to that link.
=> Update toc.md - Remove Release Notes

docs/reference/security.md
We no longer support the hidden files and gitignore file features as part of the .vsls.json.
=> Remove docs referencing hidden and gitignore files
