MicrosoftDocs/live-share

- docs/quickstart/share.md
* Add preposition for sentence coherence
* Fix run on sentence
> Update grammar for live-share getting started

- scripts/linux-prereqs.sh
This is a small refactoring of the dependencies check script for linux systems.
I tested it on Arch and it's working properly.
> Refactoring linux dependencies installation script

- scripts/linux-prereqs.sh
Fixes #292, where apt syntax was incorrect
> Fixed linux-prereqs.sh

- docs/use/vscode.md
Co-debuging, ctrl+sift+p, etc.
> Spelling and grammar fixes

- scripts/linux-prereqs.sh
- Added missing dependencies for Arch
- Added option to not install already installed packages
> More deps and no reinstallation for Archlinux

- README.md
- docs/index.md
- docs/quickstart/join.md
- docs/quickstart/share.md
- docs/use/vs.md
`an instance` instead of `a instance`
> fix a typo

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This PR enables new open-an-issue GitHub experience helping a user to file either a bug report or a feature request.
[More details...](https://help.github.com/articles/creating-issue-templates-for-your-repository/)
> Added a template for bug report

- docs/reference/manual-join.md
- Adjust heading levels not to skip
- joinign -> joining
- indentify -> identify
> fix: docs/reference/manual-join.md

- docs/reference/platform-support.md
- Double word "the"
- Double word "features"
- Use https for links
> fix: docs/reference/platform-support.md

- docs/faq.md
> fix: docs/faq.md

- docs/index.md
- potentiallty -> potentially
- Use MSDoc style alert blocks
- Trim trailing spaces
> fix: docs/index.md

- docs/reference/connectivity.md
- Use MSDoc style blockquotes
- Adjust headings for skipped levels
> fix: docs/reference/connectivity.md

- docs/quickstart/share.md
- Use MSDoc style blockquotes
- Adjust headings to not skip levels
- Adjust ordered list that skipped digets
> fix: docs/quickstart/share.md

- docs/quickstart/join.md
- Use MSDoc alert blockquote style
- Adjuste headings so levels aren't skipped
- Trim trailing spaces
> fix: docs/quickstart/join.md

- docs/user-profile.md
- Trim trailing space
- Use dash for list for consistent style
> fix: docs/user-profile.md

- docs/use/vscode.md
- Use MSDocs TIP/NOTE blockquotes
- Trim trailing spaces for Markdownlint warnings
- Adjust ordered list numbering
> fix: docs/use/vscode.md

- docs/use/vscode.md
Resolves https://github.com/MicrosoftDocs/live-share/issues/532 by copying @jasongin's response into the official documentation.
> Document liveshare.account and liveshare.accountProvider settings

- docs/use/vscode.md
This is just a boring typofix.
> Share server vs. Share terminal typofix

- docs/reference/use-cases.md
This is the first usecase that came to my mind. This is what most people use screen and tmux for besides multiplexing.
> Update use-cases to include working remotely.

- docs/reference/linux.md
In a sentence the word should be "your" instead of "you".
> Fix word to "your"

- README_jp.md
I localized README.md into Japanese.
> Japanese README

- docs/use/technical-interviews.md
https://docs.microsoft.com/en-us/visualstudio/liveshare/use/technical-interviews
> Broken link "[Live Share extension pack]"

- docs/use/vs.md
the grammar of the sentence seemed off and I believe the missing word was 'be'
> missing word 'be'

- docs/quickstart/join.md
We have increased the version requirements; we should update docs accordingly.
> Small updates on supported versions

- docs/reference/use-cases.md
See comment: https://github.com/MicrosoftDocs/live-share/pull/2786#issuecomment-693603819
This is the first usecase that came to my mind. This is what most people use screen and tmux for besides multiplexing.
> Use-cases to include working remotely

- docs/reference/manual-join.md
https://docs.microsoft.com/en-us/visualstudio/liveshare/reference/manual-join
#PingMSFTDocs
> Typo "Visual Studio Live share"→"Visual Studio Live Share"

- docs/quickstart/browser-join.md
> typo on Launcher

- docs/quickstart/join.md
- docs/quickstart/share.md
- docs/use/install-live-share-visual-studio-code.md
Closes https://github.com/MicrosoftDocs/live-share/issues/4773
> Remove 'user code'

- docs/reference/security.md
Reverting File Access and Visibility documentation back as we were able to restore former functionality.
Also added re-include note
> Update file access and visibility documentation

- docs/reference/connectivity.md
update the live share connectivity docs for VS Code
> Live Share: update connectivity docs or VS Code
